### ISSUE TITLE
Proving in zero-knowledge (private inputs)

### ISSUE THREAD

**Issue by amusgrave-via** [starkware-libs/stone-prover#8]
We are hoping to get some clarification on what in general it is possible to determine from the proof file to understand if/how the prover can be used for ZKPs. For example, the proof file begins with a "private_input" field and we have found that when using a hash function builtin (pedersen or poseidon) the hash inputs appear in this field. For our application we would like to keep these private. 

We have also found that after deleting the "private_input" section of the proof file, the proof can still be verified by cpu_air_verifier. Is this enough to make the proof a ZKP, or can other sections of the proof reveal details of the execution / private inputs?

For example, some (but not all) of the memory segments identified as "execution" appear in the proof file - do these have the potential to reveal anything about private inputs, or only public outputs / the program being verified?

Also, is there any way to prevent private inputs from being written to the proof file in the first place?

**Comment by gkaempfer** [comment]
You can safely delete the private_input and memory sections from the proof file and the verifier will still correctly verify it. Same goes for annotations of course. The proof itself is binary (the hex section in the proof file) and reveals very little input information but strictly speaking it isn't "zero knowledge" in the sense that Stone doesn't do the extra effort to randomize parts of the trace that may reveal information in the query responses. This kind of enhancement is possible, though at a bit of an overhead to the prover.

**Comment by maoudia-via** [comment]
Thank you @gkaempfer for this answer.
We would like to know:
- Is there is a plan to support this in the (near) future.
- Is there a way we could contribute to this enhancement ?

**Comment by gkaempfer** [comment]
we have no plans to support this as it isn't required for the scaling use case and practically the current proofs are used as sufficiently hiding for cases where privacy is desirable (but doesn't have to be cryptographically provable). If you have sufficient understanding of the protocol and what needs to be done to achieve ZK on Stone, you could attempt to contribute. It is a delicate task though, and as I mentioned above, it could also affect performance somewhat due to the increase in trace size.
